// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateCustomerRequest struct {
	Name        string    `json:"name"`
	DateOfBirth time.Time `json:"dateOfBirth"`
	Address     string    `json:"address"`
	Email       string    `json:"email"`
	Password    string    `json:"password"`
}

type Customer struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	DateOfBirth time.Time `json:"dateOfBirth"`
	Address     string    `json:"address"`
	Email       string    `json:"email"`
}

func (Customer) IsEntity() {}

type GetCustomerDetailsRequest struct {
	ID string `json:"id"`
}
