// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: flight.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyFlightClient is the client API for MyFlight service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyFlightClient interface {
	GetFlights(ctx context.Context, in *GetFlightsRequest, opts ...grpc.CallOption) (*GetFlightsResponse, error)
	CreateFlight(ctx context.Context, in *CreateFlightRequest, opts ...grpc.CallOption) (*Flight, error)
	UpdateFlight(ctx context.Context, in *Flight, opts ...grpc.CallOption) (*Flight, error)
	UpdateFlightAvailableSeats(ctx context.Context, in *UpdateFlightAvailableSeatsRequest, opts ...grpc.CallOption) (*Flight, error)
	GetFlightDetails(ctx context.Context, in *GetFlightDetailsRequest, opts ...grpc.CallOption) (*Flight, error)
}

type myFlightClient struct {
	cc grpc.ClientConnInterface
}

func NewMyFlightClient(cc grpc.ClientConnInterface) MyFlightClient {
	return &myFlightClient{cc}
}

func (c *myFlightClient) GetFlights(ctx context.Context, in *GetFlightsRequest, opts ...grpc.CallOption) (*GetFlightsResponse, error) {
	out := new(GetFlightsResponse)
	err := c.cc.Invoke(ctx, "/proto.MyFlight/GetFlights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myFlightClient) CreateFlight(ctx context.Context, in *CreateFlightRequest, opts ...grpc.CallOption) (*Flight, error) {
	out := new(Flight)
	err := c.cc.Invoke(ctx, "/proto.MyFlight/CreateFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myFlightClient) UpdateFlight(ctx context.Context, in *Flight, opts ...grpc.CallOption) (*Flight, error) {
	out := new(Flight)
	err := c.cc.Invoke(ctx, "/proto.MyFlight/UpdateFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myFlightClient) UpdateFlightAvailableSeats(ctx context.Context, in *UpdateFlightAvailableSeatsRequest, opts ...grpc.CallOption) (*Flight, error) {
	out := new(Flight)
	err := c.cc.Invoke(ctx, "/proto.MyFlight/UpdateFlightAvailableSeats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myFlightClient) GetFlightDetails(ctx context.Context, in *GetFlightDetailsRequest, opts ...grpc.CallOption) (*Flight, error) {
	out := new(Flight)
	err := c.cc.Invoke(ctx, "/proto.MyFlight/GetFlightDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyFlightServer is the server API for MyFlight service.
// All implementations must embed UnimplementedMyFlightServer
// for forward compatibility
type MyFlightServer interface {
	GetFlights(context.Context, *GetFlightsRequest) (*GetFlightsResponse, error)
	CreateFlight(context.Context, *CreateFlightRequest) (*Flight, error)
	UpdateFlight(context.Context, *Flight) (*Flight, error)
	UpdateFlightAvailableSeats(context.Context, *UpdateFlightAvailableSeatsRequest) (*Flight, error)
	GetFlightDetails(context.Context, *GetFlightDetailsRequest) (*Flight, error)
	mustEmbedUnimplementedMyFlightServer()
}

// UnimplementedMyFlightServer must be embedded to have forward compatible implementations.
type UnimplementedMyFlightServer struct {
}

func (UnimplementedMyFlightServer) GetFlights(context.Context, *GetFlightsRequest) (*GetFlightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlights not implemented")
}
func (UnimplementedMyFlightServer) CreateFlight(context.Context, *CreateFlightRequest) (*Flight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFlight not implemented")
}
func (UnimplementedMyFlightServer) UpdateFlight(context.Context, *Flight) (*Flight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlight not implemented")
}
func (UnimplementedMyFlightServer) UpdateFlightAvailableSeats(context.Context, *UpdateFlightAvailableSeatsRequest) (*Flight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlightAvailableSeats not implemented")
}
func (UnimplementedMyFlightServer) GetFlightDetails(context.Context, *GetFlightDetailsRequest) (*Flight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightDetails not implemented")
}
func (UnimplementedMyFlightServer) mustEmbedUnimplementedMyFlightServer() {}

// UnsafeMyFlightServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyFlightServer will
// result in compilation errors.
type UnsafeMyFlightServer interface {
	mustEmbedUnimplementedMyFlightServer()
}

func RegisterMyFlightServer(s grpc.ServiceRegistrar, srv MyFlightServer) {
	s.RegisterService(&MyFlight_ServiceDesc, srv)
}

func _MyFlight_GetFlights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyFlightServer).GetFlights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MyFlight/GetFlights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyFlightServer).GetFlights(ctx, req.(*GetFlightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyFlight_CreateFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyFlightServer).CreateFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MyFlight/CreateFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyFlightServer).CreateFlight(ctx, req.(*CreateFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyFlight_UpdateFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Flight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyFlightServer).UpdateFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MyFlight/UpdateFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyFlightServer).UpdateFlight(ctx, req.(*Flight))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyFlight_UpdateFlightAvailableSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlightAvailableSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyFlightServer).UpdateFlightAvailableSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MyFlight/UpdateFlightAvailableSeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyFlightServer).UpdateFlightAvailableSeats(ctx, req.(*UpdateFlightAvailableSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyFlight_GetFlightDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyFlightServer).GetFlightDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MyFlight/GetFlightDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyFlightServer).GetFlightDetails(ctx, req.(*GetFlightDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MyFlight_ServiceDesc is the grpc.ServiceDesc for MyFlight service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyFlight_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MyFlight",
	HandlerType: (*MyFlightServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlights",
			Handler:    _MyFlight_GetFlights_Handler,
		},
		{
			MethodName: "CreateFlight",
			Handler:    _MyFlight_CreateFlight_Handler,
		},
		{
			MethodName: "UpdateFlight",
			Handler:    _MyFlight_UpdateFlight_Handler,
		},
		{
			MethodName: "UpdateFlightAvailableSeats",
			Handler:    _MyFlight_UpdateFlightAvailableSeats_Handler,
		},
		{
			MethodName: "GetFlightDetails",
			Handler:    _MyFlight_GetFlightDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flight.proto",
}
