// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: plane.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plane struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number     string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	NumOfSeats int32  `protobuf:"varint,3,opt,name=num_of_seats,json=numOfSeats,proto3" json:"num_of_seats,omitempty"`
	Status     string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Plane) Reset() {
	*x = Plane{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plane_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plane) ProtoMessage() {}

func (x *Plane) ProtoReflect() protoreflect.Message {
	mi := &file_plane_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plane.ProtoReflect.Descriptor instead.
func (*Plane) Descriptor() ([]byte, []int) {
	return file_plane_proto_rawDescGZIP(), []int{0}
}

func (x *Plane) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plane) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Plane) GetNumOfSeats() int32 {
	if x != nil {
		return x.NumOfSeats
	}
	return 0
}

func (x *Plane) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FindPlaneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindPlaneRequest) Reset() {
	*x = FindPlaneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plane_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindPlaneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPlaneRequest) ProtoMessage() {}

func (x *FindPlaneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plane_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPlaneRequest.ProtoReflect.Descriptor instead.
func (*FindPlaneRequest) Descriptor() ([]byte, []int) {
	return file_plane_proto_rawDescGZIP(), []int{1}
}

func (x *FindPlaneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_plane_proto protoreflect.FileDescriptor

var file_plane_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f, 0x6f, 0x66, 0x5f,
	0x73, 0x65, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d,
	0x4f, 0x66, 0x53, 0x65, 0x61, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x22, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x32, 0x96, 0x01, 0x0a, 0x07, 0x4d, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12,
	0x29, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x1a, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x29, 0x0a, 0x0b, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plane_proto_rawDescOnce sync.Once
	file_plane_proto_rawDescData = file_plane_proto_rawDesc
)

func file_plane_proto_rawDescGZIP() []byte {
	file_plane_proto_rawDescOnce.Do(func() {
		file_plane_proto_rawDescData = protoimpl.X.CompressGZIP(file_plane_proto_rawDescData)
	})
	return file_plane_proto_rawDescData
}

var file_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plane_proto_goTypes = []interface{}{
	(*Plane)(nil),            // 0: proto.Plane
	(*FindPlaneRequest)(nil), // 1: proto.FindPlaneRequest
}
var file_plane_proto_depIdxs = []int32{
	0, // 0: proto.MyPlane.CreatePlane:input_type -> proto.Plane
	0, // 1: proto.MyPlane.UpdatePlane:input_type -> proto.Plane
	1, // 2: proto.MyPlane.PlaneDetails:input_type -> proto.FindPlaneRequest
	0, // 3: proto.MyPlane.CreatePlane:output_type -> proto.Plane
	0, // 4: proto.MyPlane.UpdatePlane:output_type -> proto.Plane
	0, // 5: proto.MyPlane.PlaneDetails:output_type -> proto.Plane
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plane_proto_init() }
func file_plane_proto_init() {
	if File_plane_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plane_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plane); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plane_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindPlaneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plane_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plane_proto_goTypes,
		DependencyIndexes: file_plane_proto_depIdxs,
		MessageInfos:      file_plane_proto_msgTypes,
	}.Build()
	File_plane_proto = out.File
	file_plane_proto_rawDesc = nil
	file_plane_proto_goTypes = nil
	file_plane_proto_depIdxs = nil
}
